drivers:
  - type: cli
    enabled: true
    settings: {}

  - type: json
    enabled: true
    settings:
      filename: logs.jsonl

  - type: text
    enabled: true
    settings:
      filename: logs.txt